---
title: "Sesion4"
author: "Edgar Leal"
date: "26/2/2021"
output: html_document
---

```{r}
speaqeasy_data <- file.path(tempdir(), "rse_speaqeasy.RData")
download.file("https://github.com/LieberInstitute/SPEAQeasy-example/blob/master/rse_speaqeasy.RData?raw=true", speaqeasy_data, mode = "wb")
library("SummarizedExperiment")
load(speaqeasy_data, verbose = TRUE)
```

```{r}
rse_gene
```

```{r}
rse_gene$totalAssignedGene
```

```{r}
rse_gene$mitoRate
```

```{r}
## Elimir el diagnosis "Other" porque no tiene información para poder hacer el estadístico
rse_gene$PrimaryDx <- droplevels(rse_gene$PrimaryDx)
table(rse_gene$PrimaryDx)


statistics<-model.matrix(~ totalAssignedGene + mitoRate + PrimaryDx, data=colData(rse_gene))
statistics
```

```{r}
rowRanges(rse_gene)
coord <- which(rowRanges(rse_gene)$Symbol == "SNAP25")
coord
df <- data.frame(
    Expression = assay(rse_gene)[coord, ],
    Dx = rse_gene$PrimaryDx)
df
```
```{r}
library("iSEE")
iSEE::iSEE(rse_gene)
```


```{r}
# Para el model estadístico exploremos la información de las muestras
colnames(colData(rse_gene))
## Podemos usar región del cerebro porque tenemos suficientes datos
table(rse_gene$BrainRegion)
```
```{r}
mod <- with(
    colData(rse_gene),
    model.matrix(~ PrimaryDx + totalAssignedGene + mitoRate + rRNA_rate + BrainRegion + Sex + AgeDeath)
)
## Exploremos el modelo de forma interactiva
if (interactive()) {
    ## Tenemos que eliminar columnas que tienen NAs.
    info_no_NAs <- colData(rse_gene)[, c(
        "PrimaryDx", "totalAssignedGene", "BrainRegion", "Sex",
        "mitoRate"
    )]
    ExploreModelMatrix::ExploreModelMatrix(
        info_no_NAs,
        ~ PrimaryDx + totalAssignedGene + mitoRate + rRNA_rate + BrainRegion + Sex + AgeDeath
    )
}
```

